
services:
  ms-01:
    image: "docker.io/bluehousemax/ms-01:latest"
    container_name: ms-01
    environment:
      - APP_NAME=ms-01
      - HTTP_PORT=8080
    ports:
      - "8001:8080"

  ms-02:
    image: "docker.io/bluehousemax/ms-02:latest"
    container_name: ms-02
    environment:
      - APP_NAME=ms-01
      - HTTP_PORT=8080
    ports:
      - "8002:8080"

  frontend:
    image: "docker.io/bluehousemax/frontend:latest"
    container_name: frontend
    environment:
      - URL_BFF=http://bff:8080
      - SERVER_NAME=localhost
    ports:
      - "8080:8080"

  bff:
    image: "docker.io/bluehousemax/bff:latest"
    container_name: bff
    environment:
      - APP_NAME=bff
      - HTTP_PORT=8080
      - HTTP_URL_SERVICE_01=http://ms-01:8080
      - HTTP_URL_SERVICE_02=http://ms-02:8080
    ports:
      - "8000:8080"
